# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 18:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soccer', '0003_competition_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='watch_channel_1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='watch_channel_2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='watch_url_1',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='watch_url_2',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='competition',
            name='champion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='competitions_won', to='soccer.Team'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='participants',
            field=models.ManyToManyField(related_name='competitions_participated', to='soccer.Team'),
        ),
    ]
