# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccer', '0004_auto_20170122_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='kickoff',
            field=models.DateTimeField(help_text='Local Time'),
        ),
    ]
